### ISSUE TITLE
Make UI for add-message somehow display that a message was posted.

### ISSUE THREAD

**Issue by SDeLaVida** [bhviid/GroupJ_Dev_Ops23#44]
Funktionaliteten er der, det virker, en bruger kan godt poste "twits" til databasen, meeeeen det er lidt svært at se at det rent faktisk sker :D
Hvis man poster en twit og går til public timeline, så er den nye besked der, men man kan ikke se sit nye twit på ens egen user feed/personlige timeline.

Altså, et eller andet så man ikke er i tvivl om at twit gik igennem

**Comment by tjobi** [comment]
Should be done, and pushed to develop
