### ISSUE TITLE
Enable the user to see more more tweets

### ISSUE THREAD

**Issue by bhviid** [bhviid/GroupJ_Dev_Ops23#46]
As of now you can only see the latest ~50 tweets, making the user able to keep scrolling down or add a page system would be solutions.

**Comment by tjobi** [comment]
Could this do the trick? 
https://www.meziantou.net/infinite-scrolling-in-blazor.htm

**Comment by tjobi** [comment]
Could this do the trick? 
https://www.meziantou.net/infinite-scrolling-in-blazor.htm

**Comment by tjobi** [comment]
Or this, that is simpler :) (https://learn.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-7.0)

**Comment by tjobi** [comment]
There's some primitive pagination on develop now. Hopefully we can do some infinte scroll later

**Comment by tjobi** [comment]
See PR: add virtualize component to twitdisplayer #52
